#!/usr/bin/env python3
"""Known-answer vectors for transparent_native::batched_hint.

Independent of the Rust code under test: the expected hint is computed here
with Python integers by Kronecker substitution (one exact big-integer product
per block and column, no NTT, no CRT), folded negacyclically and reduced modulo
q. Two columns per case are also recomputed by a direct schoolbook loop.

The inputs are generated by the formulas below, mirrored in the Rust test
`known_answer_vectors`. Run with no arguments to rewrite
batched_hint_kat.json beside this file; the output is deterministic.
"""
import hashlib
import json
import os

D = 2048
Q = 1 << 54
PRIMES = [1_073_692_673, 1_073_668_097, 1_073_655_809]
MASK64 = (1 << 64) - 1
SLOT_BYTES = 12  # 96-bit slots; one product coefficient is below 2^81


def splitmix64(state):
    """Yields splitmix64 outputs from `state` (Steele, Lea, Flood 2014)."""
    while True:
        state = (state + 0x9E3779B97F4A7C15) & MASK64
        z = state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        yield z ^ (z >> 31)


def case_basis():
    """Monomials only: every product is one signed, possibly wrapped term."""
    blocks = 2
    masks = [[0] * D for _ in range(blocks)]
    masks[0][D - 1] = 1  # x^(D-1)
    masks[1][5] = Q - 1  # -x^5
    data = []
    for c in range(D):
        col = [0] * (blocks * D)
        col[c % D] = 1  # block 0: x^c
        col[D + (3 * c + 1) % D] = 0xFFFF  # block 1: 65535 x^(3c+1)
        data.append(col)
    return masks, data


def case_mixed():
    """Full-width masks with forced boundary coefficients; mixed data columns."""
    blocks = 3
    rng = splitmix64(0x7472_616E_7370_6172)
    boundary = [0, 1, Q // 2 - 1, Q // 2, Q // 2 + 1, Q - 2, Q - 1, (1 << 53) + 12345]
    masks = []
    for b in range(blocks):
        mask = [next(rng) % Q for _ in range(D)]
        for i, value in enumerate(boundary):
            mask[(b * 701 + i * 257) % D] = value
        masks.append(mask)
    data = []
    for c in range(D):
        kind = c % 4
        if kind == 0:
            col = [0xFFFF] * (blocks * D)
        elif kind == 1:
            col = [0] * (blocks * D)
            col[(c * 7) % (blocks * D)] = 0xFFFF
        elif kind == 2:
            col = [next(rng) & 0xFFFF for _ in range(blocks * D)]
        else:
            col = [0xFFFF if next(rng) & 1 else 0 for _ in range(blocks * D)]
        data.append(col)
    return masks, data


def case_extreme():
    """Recent-8k's four blocks at both centered extremes: the largest sums."""
    blocks = 4
    masks = [[Q // 2 if b % 2 == 0 else Q // 2 + 1] * D for b in range(blocks)]
    rng = splitmix64(0x6578_7472_656D_6521)
    data = []
    for c in range(D):
        if c % 2 == 0:
            col = [0xFFFF] * (blocks * D)
        else:
            col = [next(rng) & 0xFFFF for _ in range(blocks * D)]
        data.append(col)
    return masks, data


def pack(poly):
    return int.from_bytes(b"".join(x.to_bytes(SLOT_BYTES, "little") for x in poly), "little")


def kronecker_column(packed_masks, col):
    out = [0] * D
    for b, packed in enumerate(packed_masks):
        product = packed * pack(col[b * D:(b + 1) * D])
        raw = product.to_bytes((2 * D) * SLOT_BYTES, "little")
        for k in range(2 * D - 1):
            term = int.from_bytes(raw[k * SLOT_BYTES:(k + 1) * SLOT_BYTES], "little")
            if k < D:
                out[k] += term
            else:
                out[k - D] -= term
    return [x % Q for x in out]


def schoolbook_column(masks, col):
    out = [0] * D
    for b, mask in enumerate(masks):
        block = col[b * D:(b + 1) * D]
        for i, m in enumerate(mask):
            if m == 0:
                continue
            for j, x in enumerate(block):
                if x == 0:
                    continue
                if i + j < D:
                    out[i + j] += m * x
                else:
                    out[i + j - D] -= m * x
    return [x % Q for x in out]


def is_prime(n):
    if n < 2:
        return False
    f = 2
    while f * f <= n:
        if n % f == 0:
            return False
        f += 1
    return True


SAMPLES = [(0, 0), (0, D - 1), (1, 0), (1, 5), (31, 17), (32, 0), (33, 2047), (1000, 1000), (2047, 0), (2047, 2046)]


def run(name, build):
    masks, data = build()
    packed = [pack(m) for m in masks]
    hint = [kronecker_column(packed, col) for col in data]
    for c in (3, 2046):
        assert schoolbook_column(masks, data[c]) == hint[c], (name, c)
    digest = hashlib.sha256()
    for col in hint:
        for x in col:
            digest.update(x.to_bytes(8, "little"))
    return {
        "name": name,
        "blocks": len(masks),
        "sha256": digest.hexdigest(),
        "samples": [[c, k, hint[c][k]] for c, k in SAMPLES],
    }


def main():
    for p in PRIMES:
        assert is_prime(p) and p < 1 << 30 and (p - 1) % (2 * D) == 0, p
    product = PRIMES[0] * PRIMES[1] * PRIMES[2]
    out = {
        "generator": "batched_hint_kat.py",
        "d": D,
        "q": Q,
        "digest": "sha256 over columns 0..D in order, each D coefficients as u64 little-endian",
        "primes_product_log2": product.bit_length(),
        "cases": [run("basis", case_basis), run("mixed", case_mixed), run("extreme", case_extreme)],
    }
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "batched_hint_kat.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=1)
        f.write("\n")


if __name__ == "__main__":
    main()
