//! Which worker holds which shards of one published set.
//!
//! A set's identity is global: shard ids, ranges and the manifest chain are
//! properties of the publication, and every worker sees the same map. What a
//! worker *holds tables for* is its assignment, a subset of the set chosen by
//! an operator tool and written down here. The two are kept apart on purpose.
//! Renumbering shards so a worker's subset looked like a whole set would break
//! the map every wallet already holds; instead a worker loads the whole map,
//! keeps every shard's manifest and filter, and verifies and serves tables only
//! for the ids assigned to it. A request for a shard it does not own is
//! answered with an explicit refusal naming the assignment, not with a guess.
//!
//! The file is generated by `shard-assign`, digested, and its digest reported
//! by every worker in `/v1/ready`, so a deploy can assert that every host is
//! running the assignment it meant to ship.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;
use transparent_filter::ShardMap;

pub const ASSIGNMENT_SCHEMA: &str = "transparent-assignment-v1";

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkerRole {
    /// Holds every shard of the recent tier, as every other replica does.
    #[serde(rename = "recent-replica")]
    RecentReplica,
    /// Holds a disjoint range of the archive tier.
    #[serde(rename = "archive-owner")]
    ArchiveOwner,
}

impl WorkerRole {
    pub fn as_str(self) -> &'static str {
        match self {
            WorkerRole::RecentReplica => "recent-replica",
            WorkerRole::ArchiveOwner => "archive-owner",
        }
    }
}

/// The publication this assignment was generated for.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SetIdentity {
    pub shard_schema: String,
    /// SHA-256 of `shards.json` as the service serializes and serves it.
    pub map_sha256: String,
    pub network: String,
    pub genesis_hash: String,
    pub shards: u64,
    pub start_height: u64,
    pub covered_through: u64,
    /// First shard id of the recent tier; every id from here is replicated.
    pub recent_from_shard: u64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedBy {
    pub tool: String,
    pub source_sha: Option<String>,
    pub generated_at: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerAssignment {
    pub id: String,
    pub role: WorkerRole,
    /// Replicas holding identical shard lists share a group; owners have none.
    pub replica_group: Option<String>,
    /// `host:port` the router reaches this worker at.
    pub upstream: String,
    /// The runtime cache budget this worker runs with.
    pub cache_bytes: u64,
    /// Ascending, unique.
    pub shards: Vec<u64>,
    /// Sum of the reservations of every assigned shard's runtimes.
    pub estimated_resident_bytes: u64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Assignment {
    pub schema: String,
    pub set: SetIdentity,
    pub generated_by: GeneratedBy,
    pub workers: Vec<WorkerAssignment>,
    /// Shards no worker holds. Explicit, so an omission is a decision.
    pub unassigned: Vec<u64>,
}

#[derive(Debug, thiserror::Error)]
pub enum AssignmentError {
    #[error("reading {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
    #[error("{path} is not a valid assignment: {source}")]
    Json {
        path: String,
        #[source]
        source: serde_json::Error,
    },
    #[error("{0}")]
    Invalid(String),
}

impl Assignment {
    pub fn load(path: &Path) -> Result<Self, AssignmentError> {
        let raw = std::fs::read(path).map_err(|source| AssignmentError::Io {
            path: path.display().to_string(),
            source,
        })?;
        let assignment: Self =
            serde_json::from_slice(&raw).map_err(|source| AssignmentError::Json {
                path: path.display().to_string(),
                source,
            })?;
        assignment.check_shape()?;
        Ok(assignment)
    }

    /// SHA-256 of the canonical serialization, the identity every worker and
    /// the deploy compare.
    pub fn digest(&self) -> String {
        hex::encode(Sha256::digest(self.canonical_bytes()))
    }

    /// Serving identity of one worker, independent of audit metadata and peers.
    /// The complete publication identity remains included: workers retain the map.
    pub fn worker_digest(&self, id: &str) -> Result<String, AssignmentError> {
        let worker = self.worker(id).ok_or_else(|| {
            AssignmentError::Invalid(format!("the assignment names no worker {id}"))
        })?;
        let bytes = serde_json::to_vec(&(
            "transparent-worker-assignment-v1",
            &self.schema,
            &self.set,
            worker,
        ))
        .expect("worker assignment serializes");
        Ok(hex::encode(Sha256::digest(bytes)))
    }

    pub fn canonical_bytes(&self) -> Vec<u8> {
        serde_json::to_vec(self).expect("an assignment serializes")
    }

    pub fn worker(&self, id: &str) -> Option<&WorkerAssignment> {
        self.workers.iter().find(|worker| worker.id == id)
    }

    /// Every worker holding `shard_id`, in file order.
    pub fn owners_of(&self, shard_id: u64) -> Vec<&WorkerAssignment> {
        self.workers
            .iter()
            .filter(|worker| worker.shards.binary_search(&shard_id).is_ok())
            .collect()
    }

    /// Internal consistency, independent of any map.
    pub fn check_shape(&self) -> Result<(), AssignmentError> {
        let invalid = |message: String| Err(AssignmentError::Invalid(message));
        if self.schema != ASSIGNMENT_SCHEMA {
            return invalid(format!(
                "assignment schema is {}, this build reads {ASSIGNMENT_SCHEMA}",
                self.schema
            ));
        }
        if self.workers.is_empty() {
            return invalid("the assignment names no workers".into());
        }
        let mut ids = BTreeSet::new();
        let mut groups: BTreeMap<&str, &[u64]> = BTreeMap::new();
        let mut archive_seen: BTreeSet<u64> = BTreeSet::new();
        for worker in &self.workers {
            if worker.id.is_empty()
                || !worker
                    .id
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
            {
                return invalid(format!("worker id {:?} is not a plain name", worker.id));
            }
            if !ids.insert(worker.id.as_str()) {
                return invalid(format!("worker {} appears twice", worker.id));
            }
            if !worker.upstream.contains(':') || worker.upstream.chars().any(char::is_whitespace) {
                return invalid(format!(
                    "worker {} upstream {:?} is not host:port",
                    worker.id, worker.upstream
                ));
            }
            if worker.shards.windows(2).any(|pair| pair[0] >= pair[1]) {
                return invalid(format!(
                    "worker {} lists shards out of order or twice",
                    worker.id
                ));
            }
            if worker.shards.iter().any(|id| *id >= self.set.shards) {
                return invalid(format!(
                    "worker {} names a shard beyond the set's {}",
                    worker.id, self.set.shards
                ));
            }
            match worker.role {
                WorkerRole::RecentReplica => {
                    let group = worker.replica_group.as_deref().ok_or_else(|| {
                        AssignmentError::Invalid(format!(
                            "recent replica {} names no replica group",
                            worker.id
                        ))
                    })?;
                    if worker
                        .shards
                        .iter()
                        .any(|id| *id < self.set.recent_from_shard)
                    {
                        return invalid(format!(
                            "recent replica {} holds an archive shard",
                            worker.id
                        ));
                    }
                    match groups.get(group) {
                        Some(held) if *held != worker.shards.as_slice() => {
                            return invalid(format!(
                                "replica group {group} holds different shard lists on different \
                                 workers"
                            ))
                        }
                        Some(_) => {}
                        None => {
                            groups.insert(group, &worker.shards);
                        }
                    }
                }
                WorkerRole::ArchiveOwner => {
                    if worker.replica_group.is_some() {
                        return invalid(format!(
                            "archive owner {} names a replica group",
                            worker.id
                        ));
                    }
                    for id in &worker.shards {
                        if *id >= self.set.recent_from_shard {
                            return invalid(format!(
                                "archive owner {} holds a recent shard",
                                worker.id
                            ));
                        }
                        if !archive_seen.insert(*id) {
                            return invalid(format!(
                                "archive shard {id} is owned by more than one worker"
                            ));
                        }
                    }
                }
            }
        }
        let mut covered: BTreeSet<u64> = self
            .workers
            .iter()
            .flat_map(|worker| worker.shards.iter().copied())
            .collect();
        for id in &self.unassigned {
            if !covered.insert(*id) {
                return invalid(format!("shard {id} is both assigned and unassigned"));
            }
        }
        for id in 0..self.set.shards {
            if !covered.contains(&id) {
                return invalid(format!(
                    "shard {id} is neither assigned nor listed as unassigned"
                ));
            }
        }
        Ok(())
    }

    /// The assignment describes exactly this map.
    pub fn check_against(&self, map: &ShardMap, map_sha256: &str) -> Result<(), AssignmentError> {
        let invalid = |message: String| Err(AssignmentError::Invalid(message));
        if self.set.map_sha256 != map_sha256 {
            return invalid(format!(
                "the assignment was generated for map {}, this set is {map_sha256}",
                self.set.map_sha256
            ));
        }
        if self.set.shard_schema != transparent_shard::manifest::SCHEMA {
            return invalid(format!(
                "the assignment names shard schema {}, this build serves {}",
                self.set.shard_schema,
                transparent_shard::manifest::SCHEMA
            ));
        }
        if self.set.network != map.network || self.set.genesis_hash != map.genesis_hash {
            return invalid("the assignment names another chain".into());
        }
        if self.set.shards != map.shards.len() as u64 {
            return invalid(format!(
                "the assignment counts {} shards, the map names {}",
                self.set.shards,
                map.shards.len()
            ));
        }
        let covered_through = map.shards.last().map(|e| e.end_height).unwrap_or(0);
        if self.set.start_height != map.start_height || self.set.covered_through != covered_through
        {
            return invalid("the assignment's range is not the map's".into());
        }
        if self.set.recent_from_shard > self.set.shards {
            return invalid("recent_from_shard is beyond the set".into());
        }
        Ok(())
    }
}

/// Rows of an assignment that concern one worker, resolved for loading.
#[derive(Clone, Debug)]
pub struct WorkerScope {
    pub worker_id: String,
    pub role: WorkerRole,
    pub replica_group: Option<String>,
    pub assignment_sha256: String,
    pub worker_assignment_sha256: String,
    pub assigned: BTreeSet<u64>,
}

impl Assignment {
    pub fn scope_for(&self, worker_id: &str) -> Result<WorkerScope, AssignmentError> {
        let worker = self.worker(worker_id).ok_or_else(|| {
            AssignmentError::Invalid(format!("the assignment names no worker {worker_id}"))
        })?;
        Ok(WorkerScope {
            worker_id: worker.id.clone(),
            role: worker.role,
            replica_group: worker.replica_group.clone(),
            assignment_sha256: self.digest(),
            worker_assignment_sha256: self.worker_digest(worker_id)?,
            assigned: worker.shards.iter().copied().collect(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn worker_identity_ignores_provenance_and_peers_but_binds_serving_state() {
        let mut a = assignment(
            vec![
                worker("owner", WorkerRole::ArchiveOwner, None, vec![0, 1]),
                worker("peer", WorkerRole::ArchiveOwner, None, vec![2, 3]),
            ],
            vec![4, 5],
        );
        let digest = a.worker_digest("owner").unwrap();
        let audit = a.digest();
        a.generated_by.generated_at.push('Z');
        a.generated_by.source_sha = Some("12".repeat(20));
        a.workers[1].upstream = "other:8093".into();
        assert_eq!(digest, a.worker_digest("owner").unwrap());
        assert_ne!(audit, a.digest());
        for change in 0..4 {
            let mut changed = a.clone();
            match change {
                0 => changed.set.map_sha256 = "34".repeat(32),
                1 => changed.workers[0].cache_bytes += 1,
                2 => changed.workers[0].shards.push(4),
                _ => changed.workers[0].upstream = "new:8093".into(),
            }
            assert_ne!(digest, changed.worker_digest("owner").unwrap());
        }
        assert!(a.worker_digest("missing").is_err());
    }

    fn worker(
        id: &str,
        role: WorkerRole,
        group: Option<&str>,
        shards: Vec<u64>,
    ) -> WorkerAssignment {
        WorkerAssignment {
            id: id.into(),
            role,
            replica_group: group.map(str::to_string),
            upstream: format!("10.0.0.{}:8093", shards.first().unwrap_or(&0) + 1),
            cache_bytes: 1 << 30,
            shards,
            estimated_resident_bytes: 0,
        }
    }

    fn assignment(workers: Vec<WorkerAssignment>, unassigned: Vec<u64>) -> Assignment {
        Assignment {
            schema: ASSIGNMENT_SCHEMA.into(),
            set: SetIdentity {
                shard_schema: transparent_shard::manifest::SCHEMA.into(),
                map_sha256: "ab".repeat(32),
                network: "main".into(),
                genesis_hash: "cd".repeat(32),
                shards: 6,
                start_height: 0,
                covered_through: 599,
                recent_from_shard: 4,
            },
            generated_by: GeneratedBy {
                tool: "test".into(),
                source_sha: None,
                generated_at: "2026-09-08T00:00:00Z".into(),
            },
            workers,
            unassigned,
        }
    }

    fn good() -> Assignment {
        assignment(
            vec![
                worker("a1", WorkerRole::ArchiveOwner, None, vec![0, 1]),
                worker("a2", WorkerRole::ArchiveOwner, None, vec![2, 3]),
                worker("r1", WorkerRole::RecentReplica, Some("recent"), vec![4, 5]),
                worker("r2", WorkerRole::RecentReplica, Some("recent"), vec![4, 5]),
            ],
            vec![],
        )
    }

    #[test]
    fn a_disjoint_covering_assignment_is_accepted_and_digests_stably() {
        let a = good();
        a.check_shape().unwrap();
        assert_eq!(a.digest(), good().digest());
        assert_eq!(a.owners_of(4).len(), 2);
        assert_eq!(a.owners_of(1).len(), 1);
        let scope = a.scope_for("a2").unwrap();
        assert_eq!(
            scope.assigned.iter().copied().collect::<Vec<_>>(),
            vec![2, 3]
        );
        assert!(a.scope_for("nobody").is_err());
    }

    #[test]
    fn overlapping_archive_owners_are_refused() {
        let mut a = good();
        a.workers[1].shards = vec![1, 2, 3];
        assert!(a.check_shape().is_err());
    }

    #[test]
    fn replicas_in_one_group_must_hold_the_same_shards() {
        let mut a = good();
        a.workers[3].shards = vec![5];
        assert!(a.check_shape().is_err());
    }

    #[test]
    fn a_shard_nobody_holds_must_be_listed_as_unassigned() {
        let mut a = good();
        a.workers[0].shards = vec![0];
        assert!(a.check_shape().is_err());
        a.unassigned = vec![1];
        a.check_shape().unwrap();
        a.workers[0].shards = vec![0, 1];
        assert!(a.check_shape().is_err(), "assigned and unassigned at once");
    }

    #[test]
    fn tiers_are_enforced_by_role() {
        let mut a = good();
        a.workers[2].shards = vec![3, 4, 5];
        assert!(
            a.check_shape().is_err(),
            "a replica holding an archive shard"
        );
        let mut a = good();
        a.workers[0].shards = vec![0, 1, 4];
        assert!(a.check_shape().is_err(), "an owner holding a recent shard");
    }
}
