//! Cross-check against filters generated by btcsuite/btcd's `gcs` package.
//!
//! `crosscheck/expected.json` was produced by a different codebase in a
//! different language (see `crosscheck/README.md` for the pinned versions and
//! the regeneration command). Expected and actual values therefore do not both
//! come from this crate, which is the point: a round trip through one
//! implementation cannot detect a shared misreading of the specification.

use transparent_filter::{build_filter, filter_hash, BlockHash, ScriptBytes};

const CASES: &str = include_str!("crosscheck/cases.json");
const EXPECTED: &str = include_str!("crosscheck/expected.json");

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    block_hash_display: String,
    elements: Vec<String>,
}

#[derive(serde::Deserialize)]
struct Expected {
    name: String,
    filter: String,
    filter_hash: String,
}

#[test]
fn filters_agree_with_the_independent_generator() {
    let cases: Vec<Case> = serde_json::from_str(CASES).expect("cases");
    let expected: Vec<Expected> = serde_json::from_str(EXPECTED).expect("expected");
    assert_eq!(
        cases.len(),
        expected.len(),
        "case and expectation counts differ"
    );
    assert!(!cases.is_empty());

    for (case, expected) in cases.iter().zip(expected.iter()) {
        assert_eq!(case.name, expected.name, "case order differs");
        let hash = BlockHash::from_display_hex(&case.block_hash_display).expect("hash");
        let elements: Vec<ScriptBytes> = case
            .elements
            .iter()
            .map(|script| ScriptBytes::new(hex::decode(script).expect("element hex")))
            .collect();
        let built = build_filter(hash, &elements).expect("build");
        assert_eq!(
            hex::encode(built.as_slice()),
            expected.filter,
            "filter bytes differ for case {}",
            case.name
        );
        assert_eq!(
            hex::encode(filter_hash(built.as_slice()).0),
            expected.filter_hash,
            "filter digest differs for case {}",
            case.name
        );
    }
}
