[package]
name = "enhance-noise-analysis"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
enhance-pir = { path = "../../crates/enhance-pir" }
enhance-pir-server = { path = "../../services/enhance-pir-server" }
ipir-sp = { git = "https://github.com/valargroup/ipir-sp.git", rev = "b1c540f90f62e112c834a0f57f025e3c605e55d1" }
inspiring = { git = "https://github.com/valargroup/ipir-sp.git", rev = "b1c540f90f62e112c834a0f57f025e3c605e55d1" }
spiral-rs = { package = "valar-spiral-rs", git = "https://github.com/valargroup/spiral-rs.git", rev = "584fee3893b1d2d17b5d774c83bd801fb70d5ace" }
rayon = "1"
serde_json = { version = "1", features = ["arbitrary_precision"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"

[profile.release]
codegen-units = 16

[profile.dev.package.valar-spiral-rs]
overflow-checks = false
opt-level = 3
