[package]
name = "enhance-noise-analysis"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
enhance-pir = { path = "../../crates/enhance-pir" }
enhance-pir-server = { path = "../../services/enhance-pir-server" }
ipir-sp = { git = "https://github.com/valargroup/ipir-sp.git", rev = "611a29284264d844bf4dba00de2874c5b762f8c2" }
inspiring = { git = "https://github.com/valargroup/ipir-sp.git", rev = "611a29284264d844bf4dba00de2874c5b762f8c2" }
spiral-rs = { package = "valar-spiral-rs", version = "=0.5.3-rc.1" }
rayon = "1"
serde_json = { version = "1", features = ["arbitrary_precision"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"

[profile.release]
codegen-units = 16

[profile.dev.package.valar-spiral-rs]
overflow-checks = false
opt-level = 3
